package com.woniu.pojo;
// Generated 2019-12-18 14:17:44 by Hibernate Tools 5.2.12.Final

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer uid;
	private String uname;
	private String upwd;
	private String role;
	private Integer pid;
	private String print;

	public User() {
	}

	public User(String uname, String upwd, String role, Integer pid, String print) {
		this.uname = uname;
		this.upwd = upwd;
		this.role = role;
		this.pid = pid;
		this.print = print;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getUpwd() {
		return this.upwd;
	}

	public void setUpwd(String upwd) {
		this.upwd = upwd;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getPrint() {
		return this.print;
	}

	public void setPrint(String print) {
		this.print = print;
	}

}
